#############################
## GitHub Actions CI Tests ##
#############################
#
# This is a reusable workflow to make CI tests more modular.
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows
#
# Called by ci-tests.yml
# This one does the dbt tests
#

name: Modular SQLFluff dbt test workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      dbt-version:
        required: true
        type: string
      coverage:
        required: false
        type: boolean
        default: false
    secrets:
      gh_token:
        required: true

jobs:
  modular-python-test:
    name: py${{ inputs.python-version }}-${{ inputs.dbt-version }}
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1

    steps:
    - uses: actions/checkout@v4

    - name: Set up Postgres
      run: docker run -d -e POSTGRES_PASSWORD=password -p 127.0.0.1:5432:5432 public.ecr.aws/docker/library/postgres

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          setup.cfg
          requirements_dev.txt

    - name: Install dependencies
      run: pip install tox

    - name: Run the tests (with coverage)
      if: ${{ inputs.coverage }}
      run: tox -e ${{ inputs.dbt-version }} -- --cov=sqlfluff_templater_dbt plugins/sqlfluff-templater-dbt

    - name: Run the tests (without coverage)
      if: ${{ !inputs.coverage }}
      run: tox -e ${{ inputs.dbt-version }} -- plugins/sqlfluff-templater-dbt
